# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [75]:
import numpy as np
import random

#### 2. Print the numpy version and the configuration (★☆☆)

In [76]:
np.__version__

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [77]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [78]:
x = np.empty((3, 3))
x.itemsize * np.empty((3, 3)).size

72

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [79]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fbbf85f73d0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [80]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [81]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [82]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [83]:
x = [i for i in range(9)]
x = np.array(x)
x.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [84]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [85]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [86]:
x = np.array([random.randint(1, 100) for i in range(27)]).reshape((3, 3, 3))
x

array([[[65, 49, 75],
        [32, 69, 32],
        [60,  7, 54]],

       [[75, 51, 49],
        [94, 23,  7],
        [59, 47, 28]],

       [[15,  8,  4],
        [54, 54, 99],
        [84, 18,  3]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [87]:
x = np.array([random.randint(1, 100) for i in range(100)]).reshape((10,10))
print(x)
print(x.max(), x.min())

[[ 70  14  26  28  33  21   8  85  68  88]
 [ 43  85  69  73   9  72  10  53  95  41]
 [ 92  91  86  65  33  59  66  71  34  43]
 [ 66  69  71  43  91  89   3  81  21  85]
 [ 75  62  95  45  19  20  50  88   4  89]
 [ 76   1  54  98  38  24  59  14  63  73]
 [ 45  50   8  13  10  73  43  56 100  28]
 [ 44  53  57  71  90  62   5  64  46  23]
 [ 38  60  14  96  96  42  10  69  64  25]
 [ 47  74  89  86  26  89  36  48   9  77]]
100 1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [88]:
x = np.array([random.randint(1, 100) for i in range(30)])
x.mean()

49.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [89]:
x = np.zeros(16).reshape(4, 4)
# x[1:len(x) - 1, 1:len(x) - 1] = 0
x[:,[0, -1]] = 1
x[[0, -1], :] = 1
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [90]:
padded_array = np.pad(x, pad_width=1, mode='constant', constant_values=0)
padded_array


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [91]:
# в чём прикол?)0))0
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [96]:
x = np.zeros((5, 5))
values = [1, 2, 3, 4]
np.fill_diagonal(x[1:], values)
x


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [97]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [98]:
x = np.zeros((8, 8))
x[::2,::2] = 1
x[1::2,1::2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [99]:
x = np.zeros((6,7,8))
idx = np.unravel_index(99, x.shape)
idx


(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [100]:
checkerboard = np.array([[0, 1], [1, 0]])
x = np.tile(checkerboard, (4, 4))
x


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [104]:
matrix = np.random.rand(5, 5)

mean, std = np.mean(matrix), np.std(matrix)

normalized_matrix = (matrix - mean) / std

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.86544884 0.93160896 0.81786064 0.22521892 0.09288913]
 [0.62503662 0.42068148 0.85628114 0.53916833 0.88262477]
 [0.33599462 0.95253303 0.92688399 0.8807991  0.3172921 ]
 [0.14119097 0.82585456 0.27879489 0.07980674 0.33442902]
 [0.16936902 0.20370945 0.94041442 0.19607925 0.09950099]]

Normalized Matrix:
[[ 1.06343687  1.26568803  0.91795998 -0.89374283 -1.29827434]
 [ 0.32849792 -0.29621474  1.03541127  0.06599898  1.1159436 ]
 [-0.55510206  1.3296528   1.25124383  1.11036255 -0.61227557]
 [-1.15061586  0.94239736 -0.72996134 -1.33826715 -0.55988808]
 [-1.06447571 -0.95949719  1.29260628 -0.98282267 -1.27806192]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [105]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color)
print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [106]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
B = np.array([[1, 2], [3, 4], [5, 6]])

C = np.dot(A, B)  
# C = A @ B
C


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [107]:
arr = np.array([1, 5, 0, 7, 8, 3, 4, 2, 8, 10])

idx = np.where((arr >= 3) & (arr <= 8))

arr[idx] = -arr[idx]

arr


array([ 1, -5,  0, -7, -8, -3, -4,  2, -8, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [108]:
# в чём прикол?)0))0
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [109]:
Z = np.array([2, 3, 4])

result1 = Z ** Z
print(result1)  

result2 = 2 << Z >> 2
print(result2)  

result3 = 1j * Z
print(result3)


[  4  27 256]
[2 4 8]
[0.+2.j 0.+3.j 0.+4.j]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [110]:
# в чём прикол?)0))0
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/12/zkzd4z3x7xx3ky2wx0r_t0y00000gp/T/ipykernel_4363/16008186.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/var/folders/12/zkzd4z3x7xx3ky2wx0r_t0y00000gp/T/ipykernel_4363/16008186.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [111]:
x = np.array([-1.5, 2.7, -3.2, 4.5])
rounded_x = np.copysign(np.ceil(np.abs(x)), x)
rounded_x


array([-2.,  3., -4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [112]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
values = np.intersect1d(a, b)
values


array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [113]:
np.seterr(all='ignore')

# Warnings

np.seterr(all='warn')


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [114]:
# в чём прикол?)0))0
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/12/zkzd4z3x7xx3ky2wx0r_t0y00000gp/T/ipykernel_4363/2233115586.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [115]:
ystrd = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tmrw= np.datetime64('today') + np.timedelta64(1)
print(ystrd, today, tmrw)


2023-03-26 2023-03-27 2023-03-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [116]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [117]:
import numpy as np

A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6], dtype=np.float64)

np.multiply(np.add(A, B, out=B), np.negative(np.divide(A, 2, out=A)), out=B)



array([ -2.5,  -7. , -13.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [118]:
arr = np.random.rand(5) * 10

int_arr1 = np.floor(arr)
int_arr2 = np.trunc(arr)
int_arr3 = arr.astype(int)
_, int_arr4 = np.modf(arr)

print("Original array:\n", arr)
print("\n np.floor():\n", int_arr1)
print("\n np.trunc():\n", int_arr2)
print("\n type casting to int:\n", int_arr3)
print("\n np.modf():\n", int_arr4)


Original array:
 [1.30593259 2.88397472 8.14311755 8.19304333 4.23535501]

 np.floor():
 [1. 2. 8. 8. 4.]

 np.trunc():
 [1. 2. 8. 8. 4.]

 type casting to int:
 [1 2 8 8 4]

 np.modf():
 [1. 2. 8. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [119]:
row = np.arange(5)

x = row[np.newaxis, :].repeat(5, axis=0)
x


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

Yield - это ключевое слово в Python, которое используется для возврата из функции с сохранением состояния ее локальных переменных, 
и при повторном вызове такой функции выполнение продолжается с оператора yield, на котором ее работа была прервана.

In [137]:
def generate_integers():
    for i in range(10):
        yield i

arr = np.fromiter(generate_integers(), dtype=int)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [121]:
vector = np.linspace(0, 1, num=10, endpoint=False)
vector

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [122]:
v = np.random.rand(10)
np.sort(v)

array([0.11024322, 0.15701713, 0.21636193, 0.28083189, 0.35938212,
       0.46248667, 0.54042227, 0.70742856, 0.76060834, 0.9825238 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [123]:
%%time
arr = np.array([1, 2, 3, 4, 5])
total = 0
for i in range(len(arr)):
    total += arr[i]
total

CPU times: user 66 µs, sys: 0 ns, total: 66 µs
Wall time: 72.2 µs


15

In [124]:
%%time
arr = np.array([1, 2, 3, 4, 5])
np.sum(arr)

CPU times: user 201 µs, sys: 2 µs, total: 203 µs
Wall time: 213 µs


15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [125]:
A = np.random.rand(3, 4)
B = np.random.rand(3, 4)
print("equal") if np.array_equal(A, B) else print("not equal")


not equal


#### 43. Make an array immutable (read-only) (★★☆)

In [126]:
a = np.array([1, 2, 3, 4, 5])

a.flags.writeable = False

try:
    a[0] = 0  # ValueError: assignment destination is read-only
except:
    print('Не надо так')

Не надо так


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

r = sqrt(x^2 + y^2)

theta = arctan(y/x)

In [127]:
cartesian_coords = np.random.rand(10, 2)

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coords = np.column_stack((r, theta))

print("Cartesian coordinates:\n", cartesian_coords)
print("\n")
print("Polar coordinates:\n", polar_coords)


Cartesian coordinates:
 [[0.31312938 0.29657357]
 [0.53003237 0.47978963]
 [0.96764174 0.18384387]
 [0.36794057 0.09284927]
 [0.02378755 0.27518475]
 [0.00301813 0.85193522]
 [0.68969233 0.11056905]
 [0.10320516 0.94593135]
 [0.84641958 0.80016589]
 [0.10924225 0.5107451 ]]


Polar coordinates:
 [[0.431284   0.75825095]
 [0.71493524 0.7356851 ]
 [0.98495132 0.18775391]
 [0.37947496 0.24718784]
 [0.27621095 1.48456858]
 [0.85194057 1.56725366]
 [0.69849912 0.15896383]
 [0.95154476 1.4621219 ]
 [1.16477103 0.75731488]
 [0.52229725 1.36008328]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [128]:
v = np.random.rand(10)
print(v)

max_idx = np.argmax(v)
v[max_idx] = 0

print(v)


[0.02453372 0.81189341 0.67795162 0.78687767 0.06880441 0.73195203
 0.97788156 0.82584215 0.59344447 0.25627144]
[0.02453372 0.81189341 0.67795162 0.78687767 0.06880441 0.73195203
 0.         0.82584215 0.59344447 0.25627144]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [129]:
x, y = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

coords = np.zeros((x.size,), dtype=[('x', np.float32), ('y', np.float32)])
coords['x'] = x.flatten()
coords['y'] = y.flatten()

print(coords)


[(0.        , 0.        ) (0.11111111, 0.        )
 (0.22222222, 0.        ) (0.33333334, 0.        )
 (0.44444445, 0.        ) (0.5555556 , 0.        )
 (0.6666667 , 0.        ) (0.7777778 , 0.        )
 (0.8888889 , 0.        ) (1.        , 0.        )
 (0.        , 0.11111111) (0.11111111, 0.11111111)
 (0.22222222, 0.11111111) (0.33333334, 0.11111111)
 (0.44444445, 0.11111111) (0.5555556 , 0.11111111)
 (0.6666667 , 0.11111111) (0.7777778 , 0.11111111)
 (0.8888889 , 0.11111111) (1.        , 0.11111111)
 (0.        , 0.22222222) (0.11111111, 0.22222222)
 (0.22222222, 0.22222222) (0.33333334, 0.22222222)
 (0.44444445, 0.22222222) (0.5555556 , 0.22222222)
 (0.6666667 , 0.22222222) (0.7777778 , 0.22222222)
 (0.8888889 , 0.22222222) (1.        , 0.22222222)
 (0.        , 0.33333334) (0.11111111, 0.33333334)
 (0.22222222, 0.33333334) (0.33333334, 0.33333334)
 (0.44444445, 0.33333334) (0.5555556 , 0.33333334)
 (0.6666667 , 0.33333334) (0.7777778 , 0.33333334)
 (0.8888889 , 0.33333334) (1.  

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [130]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

diffs = X[:, np.newaxis] - Y

C = 1.0 / diffs
C


array([[-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [131]:
print("Minimum and maximum values for integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: {info.min}, {info.max}")
    
print("\nMinimum and maximum values for floating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: {info.min}, {info.max}")


Minimum and maximum values for integer types:
int8: -128, 127
int16: -32768, 32767
int32: -2147483648, 2147483647
int64: -9223372036854775808, 9223372036854775807

Minimum and maximum values for floating-point types:
float16: -65504.0, 65504.0
float32: -3.4028234663852886e+38, 3.4028234663852886e+38
float64: -1.7976931348623157e+308, 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [142]:
np.set_printoptions(threshold=float("inf"))
x = np.empty((20,20))
x


array([[ 0.00000000e+000,  4.10074486e-322,  0.00000000e+000,
         6.93894627e-310,  0.00000000e+000,              nan,
                     nan,              nan,              nan,
         0.00000000e+000,  4.44659081e-323,  6.93892069e-310,
         6.93894627e-310,  9.88131292e-324,  0.00000000e+000,
                     nan,  0.00000000e+000,  6.93892624e-310,
         3.55727265e-322,  5.43472210e-323],
       [ 6.93892053e-310,  6.93894117e-310,  9.88131292e-324,
         4.94065646e-323,              nan,  0.00000000e+000,
         6.93892624e-310,  7.11454530e-322,  5.43472210e-323,
         6.93892053e-310,  6.93894117e-310,              nan,
         1.28457068e-322,              nan,  0.00000000e+000,
         6.93892624e-310,  1.06718180e-321,  5.43472210e-323,
         6.93892053e-310,  6.93894117e-310],
       [ 9.88131292e-324,  1.28457068e-322,              nan,
         0.00000000e+000,  4.94065646e-324,  1.42290906e-321,
         5.43472210e-323,  6.93892053e-310

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [133]:
v = np.random.rand(10)

scalar = 0.5
idx = np.abs(v - scalar).argmin()

closest_value = v[idx]

print("Vector:", v)
print("Scalar:", scalar)
print("Closest value:", closest_value)

Vector: [0.53103896 0.71433851 0.16200724 0.53506793 0.75644153 0.63409441
 0.97026641 0.56015657 0.60415434 0.80491684]
Scalar: 0.5
Closest value: 0.5310389598181391


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)